version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "ap-northeast-1"
capabilities = "CAPABILITY_NAMED_IAM"
parameter_overrides = "Environment=\"dev\""
stack_name = "LINEsampleBatch"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m014qmwqbf5l"
s3_prefix = "LINEsampleBatch"
confirm_changeset = true
disable_rollback = true
image_repositories = []

