version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
region = "ap-northeast-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
stack_name = "LINEsampleLayer"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-m014qmwqbf5l"
s3_prefix = "LINEsampleLayer"
confirm_changeset = true
disable_rollback = true
image_repositories = []


[y]
[y.deploy]
[y.deploy.parameters]
stack_name = "sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-129gzi4za9nn0"
s3_prefix = "sam-app"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=\"dev\""
image_repositories = []
